# Generated by Django 5.2.3 on 2025-07-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Designates whether this furniture item should be visible on the website.'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(help_text='A URL-friendly identifier for the brand, automatically generated if left blank.', unique=True),
        ),
    ]
