# Generated by Django 5.2.3 on 2025-07-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_furniture_is_visible_alter_brand_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('INHOUSE', 'Inhouse'), ('CLASSIC', 'Classic'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('VVIP', 'VVIP')], max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='member_levels/')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowance', models.DecimalField(decimal_places=2, help_text='Allowance for this level', max_digits=12)),
            ],
        ),
    ]
