# Generated by Django 5.2.3 on 2025-07-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
