# Generated by Django 5.2.3 on 2025-07-24 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_sponsor_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10, unique=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['currency'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='member_level',
            field=models.CharField(choices=[('INHOUSE', 'Inhouse'), ('CLASSIC', 'Classic'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('VVIP', 'VVIP')], default='Bronze', max_length=10),
        ),
        migrations.CreateModel(
            name='ExchangeRateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='Currency code at the time of the log.', max_length=10)),
                ('old_rate', models.DecimalField(decimal_places=4, help_text='Old exchange rate before the change.', max_digits=10)),
                ('new_rate', models.DecimalField(decimal_places=4, help_text='New exchange rate after the change.', max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exchange_rate', models.ForeignKey(blank=True, help_text='The exchange rate that was affected (can be null if rate was deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.exchangerate')),
            ],
            options={
                'verbose_name': 'Exchange Rate Log',
                'verbose_name_plural': 'Exchange Rate Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], help_text='Type of action performed on the order.', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='The order that was affected (can be null if order was deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
            ],
            options={
                'verbose_name': 'Order Log',
                'verbose_name_plural': 'Order Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SponsorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(help_text='Name of the sponsor at the time of the log.', max_length=100)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], help_text='Type of action performed on the sponsor.', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(blank=True, help_text='The sponsor that was affected (can be null if sponsor was deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.sponsor')),
            ],
            options={
                'verbose_name': 'Sponsor Log',
                'verbose_name_plural': 'Sponsor Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
