# Generated by Django 5.2.3 on 2025-07-24 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_exchangerate_alter_customuser_member_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['currency'], 'verbose_name': 'Exchange Rate', 'verbose_name_plural': 'Exchange Rates'},
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who last created or modified this exchange rate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_rates_changed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(help_text='e.g., USD, EUR, JPY', max_length=3, unique=True),
        ),
    ]
