# Generated by Django 5.2.3 on 2025-07-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_exchangerate_options_exchangerate_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exchangeratelog',
            name='new_rate',
            field=models.DecimalField(decimal_places=2, help_text='New exchange rate after the change.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='exchangeratelog',
            name='old_rate',
            field=models.DecimalField(decimal_places=2, help_text='Old exchange rate before the change.', max_digits=10),
        ),
    ]
