# Generated by Django 5.2.3 on 2025-07-05 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('texture_body', models.ImageField(blank=True, null=True, upload_to='materials/body/')),
                ('texture_door', models.ImageField(blank=True, null=True, upload_to='materials/door/')),
                ('accessory_handle', models.ImageField(blank=True, null=True, upload_to='materials/accessory/')),
                ('color_hex', models.CharField(default='#8B4513', max_length=7)),
                ('price_per_sqft', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='WardrobeDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('depth', models.FloatField()),
                ('shelf_count', models.IntegerField(default=3)),
                ('shelf_color_hex', models.CharField(default='#D2B48C', max_length=7)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessory_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_designs', to='customize.material')),
                ('body_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_designs', to='customize.material')),
                ('door_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_designs', to='customize.material')),
                ('shelf_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelf_designs', to='customize.material')),
            ],
        ),
    ]
