# Generated by Django 5.2.3 on 2025-07-05 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AlterModelOptions(
            name='wardrobedesign',
            options={'verbose_name': 'Wardrobe Design', 'verbose_name_plural': 'Wardrobe Designs'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='accessory_handle',
        ),
        migrations.RemoveField(
            model_name='wardrobedesign',
            name='accessory_material',
        ),
        migrations.AddField(
            model_name='material',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per single unit for accessories like handles.', max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='texture_handle',
            field=models.ImageField(blank=True, help_text='Texture for the handles.', null=True, upload_to='materials/textures/handle/'),
        ),
        migrations.AddField(
            model_name='wardrobedesign',
            name='handle_count',
            field=models.IntegerField(default=2, help_text='Number of handles for the wardrobe.'),
        ),
        migrations.AddField(
            model_name='wardrobedesign',
            name='handle_material',
            field=models.ForeignKey(blank=True, help_text="Select the material for the handles. Its 'texture_handle' will be used.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handle_designs', to='customize.material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='color_hex',
            field=models.CharField(default='#8B4513', help_text='Hexadecimal color code (e.g., #RRGGBB).', max_length=7),
        ),
        migrations.AlterField(
            model_name='material',
            name='price_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per square foot for body/door/shelf usage.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='texture_body',
            field=models.ImageField(blank=True, help_text="Texture for the wardrobe's main body.", null=True, upload_to='materials/textures/body/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='texture_door',
            field=models.ImageField(blank=True, help_text='Texture for the wardrobe doors.', null=True, upload_to='materials/textures/door/'),
        ),
        migrations.AlterField(
            model_name='wardrobedesign',
            name='body_material',
            field=models.ForeignKey(help_text='Select the material for the main body/carcass of the wardrobe.', on_delete=django.db.models.deletion.CASCADE, related_name='body_designs', to='customize.material'),
        ),
        migrations.AlterField(
            model_name='wardrobedesign',
            name='depth',
            field=models.FloatField(help_text='Depth of the wardrobe in feet (e.g., 2.0).'),
        ),
        migrations.AlterField(
            model_name='wardrobedesign',
            name='door_material',
            field=models.ForeignKey(help_text='Select the material for the wardrobe doors.', on_delete=django.db.models.deletion.CASCADE, related_name='door_designs', to='customize.material'),
        ),
        migrations.AlterField(
            model_name='wardrobedesign',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Automatically calculated estimated cost of the design.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wardrobedesign',
            name='height',
            field=models.FloatField(help_text='Height of the wardrobe in feet (e.g., 7.5).'),
        ),
        migrations.AlterField(
            model_name='wardrobedesign',
            name='shelf_color_hex',
            field=models.CharField(default='#D2B48C', help_text="Hexadecimal color for shelves if 'shelf_material' doesn't dictate it.", max_length=7),
        ),
        migrations.AlterField(
            model_name='wardrobedesign',
            name='shelf_count',
            field=models.IntegerField(default=3, help_text='Number of internal shelves.'),
        ),
        migrations.AlterField(
            model_name='wardrobedesign',
            name='shelf_material',
            field=models.ForeignKey(blank=True, help_text='Select the material for the internal shelves.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelf_designs', to='customize.material'),
        ),
        migrations.AlterField(
            model_name='wardrobedesign',
            name='width',
            field=models.FloatField(help_text='Width of the wardrobe in feet (e.g., 5.0).'),
        ),
    ]
